CREATE TABLE `ru`.`avaliacoes` 
    (`ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT , 
    `DATA_HORA` DATETIME NOT NULL , 
    `VG_OTIMO` INT(11) UNSIGNED NOT NULL DEFAULT '0' ,
    `VG_RUIM` INT(11) UNSIGNED NOT NULL DEFAULT '0' , 
    `VG_BOM` INT(11) UNSIGNED NOT NULL DEFAULT '0' ,
    `CB_OTIMO` INT(11) UNSIGNED NOT NULL DEFAULT '0' , 
    `CB_RUIM` INT(11) UNSIGNED NOT NULL DEFAULT '0' , 
    `CB_BOM` INT(11) UNSIGNED NOT NULL DEFAULT '0' ,
    `CVM_OTIMO` INT(11) UNSIGNED NOT NULL DEFAULT '0' ,
    `CVM_RUIM` INT(11) UNSIGNED NOT NULL DEFAULT '0' ,
    `CVM_BOM` INT(11) UNSIGNED NOT NULL DEFAULT '0' , 
    `TOTAL` INT(11) UNSIGNED NOT NULL DEFAULT '0' , 
    PRIMARY KEY (`ID`), UNIQUE `UNIQUE` (`DATA_HORA`)) ENGINE = InnoDB;